STATUS_ERROR = 0
STATUS_ARMED_AWAY = 1
STATUS_ARMED_STAY = 2
STATUS_DISARMED = 3
STATUS_CANCEL_ALARM = 4

MAX_ZONES = 40

ZONE_TYPE_DISABLED = 0
ZONE_TYPE_DELAYED = 1
ZONE_TYPE_PERIMETER = 2
ZONE_TYPE_INTERNAL = 3
ZONE_TYPE_EMERGENCY = 4
ZONE_TYPE_24HR = 5
ZONE_TYPE_SMOKE = 6
ZONE_TYPE_KEY = 7

ALARM_MODE_FIX = 1
ALARM_MODE_PULSE = 2
ALARM_MODE_SILENT = 3


